* Fixed VS 2005 solution file, which had an incorrect reference to ConnectionStringHelper.cs ("error CS2001: Source file '..\..\Elmah\Assertions\ConnectionStringHelper.cs' could not be found)").